// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: packetloss/v1/artifacts.proto

package packetlossv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---- countries.json ----
type CountryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeneratedAt   string                 `protobuf:"bytes,1,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"` // RFC3339
	Countries     []*CountrySummary      `protobuf:"bytes,2,rep,name=countries,proto3" json:"countries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountryList) Reset() {
	*x = CountryList{}
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryList) ProtoMessage() {}

func (x *CountryList) ProtoReflect() protoreflect.Message {
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryList.ProtoReflect.Descriptor instead.
func (*CountryList) Descriptor() ([]byte, []int) {
	return file_packetloss_v1_artifacts_proto_rawDescGZIP(), []int{0}
}

func (x *CountryList) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *CountryList) GetCountries() []*CountrySummary {
	if x != nil {
		return x.Countries
	}
	return nil
}

type CountrySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // ISO country code, lower-case (matches URL segment)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProviderCount uint32                 `protobuf:"varint,3,opt,name=provider_count,json=providerCount,proto3" json:"provider_count,omitempty"`
	TargetCount   uint32                 `protobuf:"varint,4,opt,name=target_count,json=targetCount,proto3" json:"target_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountrySummary) Reset() {
	*x = CountrySummary{}
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountrySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountrySummary) ProtoMessage() {}

func (x *CountrySummary) ProtoReflect() protoreflect.Message {
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountrySummary.ProtoReflect.Descriptor instead.
func (*CountrySummary) Descriptor() ([]byte, []int) {
	return file_packetloss_v1_artifacts_proto_rawDescGZIP(), []int{1}
}

func (x *CountrySummary) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CountrySummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CountrySummary) GetProviderCount() uint32 {
	if x != nil {
		return x.ProviderCount
	}
	return 0
}

func (x *CountrySummary) GetTargetCount() uint32 {
	if x != nil {
		return x.TargetCount
	}
	return 0
}

// ---- <country>/overview.json : the ranking grid ----
type Overview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CountryName   string                 `protobuf:"bytes,2,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty"`
	GeneratedAt   string                 `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	Targets       []*TargetRef           `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`     // column order
	Providers     []*ProviderRow         `protobuf:"bytes,5,rep,name=providers,proto3" json:"providers,omitempty"` // pre-sorted by score, best first
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Overview) Reset() {
	*x = Overview{}
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Overview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Overview) ProtoMessage() {}

func (x *Overview) ProtoReflect() protoreflect.Message {
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Overview.ProtoReflect.Descriptor instead.
func (*Overview) Descriptor() ([]byte, []int) {
	return file_packetloss_v1_artifacts_proto_rawDescGZIP(), []int{2}
}

func (x *Overview) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Overview) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

func (x *Overview) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *Overview) GetTargets() []*TargetRef {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Overview) GetProviders() []*ProviderRow {
	if x != nil {
		return x.Providers
	}
	return nil
}

type TargetRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // hyperscaler | cloud | eyeball
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetRef) Reset() {
	*x = TargetRef{}
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRef) ProtoMessage() {}

func (x *TargetRef) ProtoReflect() protoreflect.Message {
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRef.ProtoReflect.Descriptor instead.
func (*TargetRef) Descriptor() ([]byte, []int) {
	return file_packetloss_v1_artifacts_proto_rawDescGZIP(), []int{3}
}

func (x *TargetRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TargetRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TargetRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ProviderRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`                            // 0..10 overall (mean of cell scores)
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=packetloss.v1.Status" json:"status,omitempty"` // overall roll-up
	Covered       bool                   `protobuf:"varint,5,opt,name=covered,proto3" json:"covered,omitempty"`                         // false => insufficient probe coverage
	ProbeCount    uint32                 `protobuf:"varint,6,opt,name=probe_count,json=probeCount,proto3" json:"probe_count,omitempty"`
	Cells         []*Cell                `protobuf:"bytes,7,rep,name=cells,proto3" json:"cells,omitempty"` // aligned to Overview.targets order
	Kind          string                 `protobuf:"bytes,8,opt,name=kind,proto3" json:"kind,omitempty"`   // eyeball | transit | content | ixp (network class; for frontend filtering)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderRow) Reset() {
	*x = ProviderRow{}
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderRow) ProtoMessage() {}

func (x *ProviderRow) ProtoReflect() protoreflect.Message {
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderRow.ProtoReflect.Descriptor instead.
func (*ProviderRow) Descriptor() ([]byte, []int) {
	return file_packetloss_v1_artifacts_proto_rawDescGZIP(), []int{4}
}

func (x *ProviderRow) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *ProviderRow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderRow) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ProviderRow) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *ProviderRow) GetCovered() bool {
	if x != nil {
		return x.Covered
	}
	return false
}

func (x *ProviderRow) GetProbeCount() uint32 {
	if x != nil {
		return x.ProbeCount
	}
	return 0
}

func (x *ProviderRow) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *ProviderRow) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=packetloss.v1.Status" json:"status,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	RttP50Ms      float64                `protobuf:"fixed64,4,opt,name=rtt_p50_ms,json=rttP50Ms,proto3" json:"rtt_p50_ms,omitempty"`
	LossPct       float64                `protobuf:"fixed64,5,opt,name=loss_pct,json=lossPct,proto3" json:"loss_pct,omitempty"`
	HasData       bool                   `protobuf:"varint,6,opt,name=has_data,json=hasData,proto3" json:"has_data,omitempty"`
	JitterMs      float64                `protobuf:"fixed64,7,opt,name=jitter_ms,json=jitterMs,proto3" json:"jitter_ms,omitempty"` // mean consecutive RTT deviation (RFC3550-style) over the window
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_packetloss_v1_artifacts_proto_rawDescGZIP(), []int{5}
}

func (x *Cell) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Cell) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Cell) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Cell) GetRttP50Ms() float64 {
	if x != nil {
		return x.RttP50Ms
	}
	return 0
}

func (x *Cell) GetLossPct() float64 {
	if x != nil {
		return x.LossPct
	}
	return 0
}

func (x *Cell) GetHasData() bool {
	if x != nil {
		return x.HasData
	}
	return false
}

func (x *Cell) GetJitterMs() float64 {
	if x != nil {
		return x.JitterMs
	}
	return 0
}

// ---- <country>/providers/<asn>.json : the provider detail page ----
type ProviderDetail struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CountryCode string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Asn         uint32                 `protobuf:"varint,2,opt,name=asn,proto3" json:"asn,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Score       float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Status      Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=packetloss.v1.Status" json:"status,omitempty"`
	Covered     bool                   `protobuf:"varint,6,opt,name=covered,proto3" json:"covered,omitempty"`
	ProbeCount  uint32                 `protobuf:"varint,7,opt,name=probe_count,json=probeCount,proto3" json:"probe_count,omitempty"`
	GeneratedAt string                 `protobuf:"bytes,8,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	Targets     []*TargetSeries        `protobuf:"bytes,9,rep,name=targets,proto3" json:"targets,omitempty"`
	// RIPE Atlas probe IDs (inside this ASN) whose results fed the score; link to
	// /probes/<id>/. Distinct + sorted. Empty when the provider isn't covered.
	ProbeIds      []uint32 `protobuf:"varint,10,rep,packed,name=probe_ids,json=probeIds,proto3" json:"probe_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderDetail) Reset() {
	*x = ProviderDetail{}
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderDetail) ProtoMessage() {}

func (x *ProviderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderDetail.ProtoReflect.Descriptor instead.
func (*ProviderDetail) Descriptor() ([]byte, []int) {
	return file_packetloss_v1_artifacts_proto_rawDescGZIP(), []int{6}
}

func (x *ProviderDetail) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *ProviderDetail) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *ProviderDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderDetail) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ProviderDetail) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *ProviderDetail) GetCovered() bool {
	if x != nil {
		return x.Covered
	}
	return false
}

func (x *ProviderDetail) GetProbeCount() uint32 {
	if x != nil {
		return x.ProbeCount
	}
	return 0
}

func (x *ProviderDetail) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *ProviderDetail) GetTargets() []*TargetSeries {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *ProviderDetail) GetProbeIds() []uint32 {
	if x != nil {
		return x.ProbeIds
	}
	return nil
}

type TargetSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetName    string                 `protobuf:"bytes,2,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=packetloss.v1.Status" json:"status,omitempty"`
	Series        []*TimePoint           `protobuf:"bytes,5,rep,name=series,proto3" json:"series,omitempty"`                                     // small RTT+loss chart
	MeasurementId uint32                 `protobuf:"varint,7,opt,name=measurement_id,json=measurementId,proto3" json:"measurement_id,omitempty"` // RIPE Atlas measurement for this target; link to /measurements/<id>/
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetSeries) Reset() {
	*x = TargetSeries{}
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetSeries) ProtoMessage() {}

func (x *TargetSeries) ProtoReflect() protoreflect.Message {
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetSeries.ProtoReflect.Descriptor instead.
func (*TargetSeries) Descriptor() ([]byte, []int) {
	return file_packetloss_v1_artifacts_proto_rawDescGZIP(), []int{7}
}

func (x *TargetSeries) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *TargetSeries) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *TargetSeries) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TargetSeries) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *TargetSeries) GetSeries() []*TimePoint {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *TargetSeries) GetMeasurementId() uint32 {
	if x != nil {
		return x.MeasurementId
	}
	return 0
}

// ---- <country>/targets/<id>.json : the target comparison page ----
type TargetComparison struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CountryCode    string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	TargetId       string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetName     string                 `protobuf:"bytes,3,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	Kind           string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	GeneratedAt    string                 `protobuf:"bytes,5,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	Providers      []*ProviderSeries      `protobuf:"bytes,6,rep,name=providers,proto3" json:"providers,omitempty"`                                    // overlaid lines, best first
	MeasurementId  uint32                 `protobuf:"varint,7,opt,name=measurement_id,json=measurementId,proto3" json:"measurement_id,omitempty"`      // RIPE Atlas measurement for this target; link to /measurements/<id>/
	Target         string                 `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`                                          // RIPE ping target: hostname (resolved per-probe) or pinned IP
	ResolveOnProbe bool                   `protobuf:"varint,9,opt,name=resolve_on_probe,json=resolveOnProbe,proto3" json:"resolve_on_probe,omitempty"` // true => hostname resolved at each probe (anycast/CDN nearest edge)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TargetComparison) Reset() {
	*x = TargetComparison{}
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetComparison) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetComparison) ProtoMessage() {}

func (x *TargetComparison) ProtoReflect() protoreflect.Message {
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetComparison.ProtoReflect.Descriptor instead.
func (*TargetComparison) Descriptor() ([]byte, []int) {
	return file_packetloss_v1_artifacts_proto_rawDescGZIP(), []int{8}
}

func (x *TargetComparison) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *TargetComparison) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *TargetComparison) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *TargetComparison) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TargetComparison) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *TargetComparison) GetProviders() []*ProviderSeries {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *TargetComparison) GetMeasurementId() uint32 {
	if x != nil {
		return x.MeasurementId
	}
	return 0
}

func (x *TargetComparison) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TargetComparison) GetResolveOnProbe() bool {
	if x != nil {
		return x.ResolveOnProbe
	}
	return false
}

type ProviderSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=packetloss.v1.Status" json:"status,omitempty"`
	Series        []*TimePoint           `protobuf:"bytes,5,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderSeries) Reset() {
	*x = ProviderSeries{}
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSeries) ProtoMessage() {}

func (x *ProviderSeries) ProtoReflect() protoreflect.Message {
	mi := &file_packetloss_v1_artifacts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSeries.ProtoReflect.Descriptor instead.
func (*ProviderSeries) Descriptor() ([]byte, []int) {
	return file_packetloss_v1_artifacts_proto_rawDescGZIP(), []int{9}
}

func (x *ProviderSeries) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *ProviderSeries) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderSeries) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ProviderSeries) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *ProviderSeries) GetSeries() []*TimePoint {
	if x != nil {
		return x.Series
	}
	return nil
}

var File_packetloss_v1_artifacts_proto protoreflect.FileDescriptor

const file_packetloss_v1_artifacts_proto_rawDesc = "" +
	"\n" +
	"\x1dpacketloss/v1/artifacts.proto\x12\rpacketloss.v1\x1a\x1apacketloss/v1/common.proto\"m\n" +
	"\vCountryList\x12!\n" +
	"\fgenerated_at\x18\x01 \x01(\tR\vgeneratedAt\x12;\n" +
	"\tcountries\x18\x02 \x03(\v2\x1d.packetloss.v1.CountrySummaryR\tcountries\"\x82\x01\n" +
	"\x0eCountrySummary\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eprovider_count\x18\x03 \x01(\rR\rproviderCount\x12!\n" +
	"\ftarget_count\x18\x04 \x01(\rR\vtargetCount\"\xe1\x01\n" +
	"\bOverview\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12!\n" +
	"\fcountry_name\x18\x02 \x01(\tR\vcountryName\x12!\n" +
	"\fgenerated_at\x18\x03 \x01(\tR\vgeneratedAt\x122\n" +
	"\atargets\x18\x04 \x03(\v2\x18.packetloss.v1.TargetRefR\atargets\x128\n" +
	"\tproviders\x18\x05 \x03(\v2\x1a.packetloss.v1.ProviderRowR\tproviders\"C\n" +
	"\tTargetRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"\xf2\x01\n" +
	"\vProviderRow\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.packetloss.v1.StatusR\x06status\x12\x18\n" +
	"\acovered\x18\x05 \x01(\bR\acovered\x12\x1f\n" +
	"\vprobe_count\x18\x06 \x01(\rR\n" +
	"probeCount\x12)\n" +
	"\x05cells\x18\a \x03(\v2\x13.packetloss.v1.CellR\x05cells\x12\x12\n" +
	"\x04kind\x18\b \x01(\tR\x04kind\"\xd9\x01\n" +
	"\x04Cell\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.packetloss.v1.StatusR\x06status\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x1c\n" +
	"\n" +
	"rtt_p50_ms\x18\x04 \x01(\x01R\brttP50Ms\x12\x19\n" +
	"\bloss_pct\x18\x05 \x01(\x01R\alossPct\x12\x19\n" +
	"\bhas_data\x18\x06 \x01(\bR\ahasData\x12\x1b\n" +
	"\tjitter_ms\x18\a \x01(\x01R\bjitterMs\"\xd0\x02\n" +
	"\x0eProviderDetail\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12\x10\n" +
	"\x03asn\x18\x02 \x01(\rR\x03asn\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.packetloss.v1.StatusR\x06status\x12\x18\n" +
	"\acovered\x18\x06 \x01(\bR\acovered\x12\x1f\n" +
	"\vprobe_count\x18\a \x01(\rR\n" +
	"probeCount\x12!\n" +
	"\fgenerated_at\x18\b \x01(\tR\vgeneratedAt\x125\n" +
	"\atargets\x18\t \x03(\v2\x1b.packetloss.v1.TargetSeriesR\atargets\x12\x1b\n" +
	"\tprobe_ids\x18\n" +
	" \x03(\rR\bprobeIds\"\xf0\x01\n" +
	"\fTargetSeries\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x1f\n" +
	"\vtarget_name\x18\x02 \x01(\tR\n" +
	"targetName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.packetloss.v1.StatusR\x06status\x120\n" +
	"\x06series\x18\x05 \x03(\v2\x18.packetloss.v1.TimePointR\x06series\x12%\n" +
	"\x0emeasurement_id\x18\a \x01(\rR\rmeasurementIdJ\x04\b\x06\x10\a\"\xd0\x02\n" +
	"\x10TargetComparison\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x1f\n" +
	"\vtarget_name\x18\x03 \x01(\tR\n" +
	"targetName\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12!\n" +
	"\fgenerated_at\x18\x05 \x01(\tR\vgeneratedAt\x12;\n" +
	"\tproviders\x18\x06 \x03(\v2\x1d.packetloss.v1.ProviderSeriesR\tproviders\x12%\n" +
	"\x0emeasurement_id\x18\a \x01(\rR\rmeasurementId\x12\x16\n" +
	"\x06target\x18\b \x01(\tR\x06target\x12(\n" +
	"\x10resolve_on_probe\x18\t \x01(\bR\x0eresolveOnProbe\"\xad\x01\n" +
	"\x0eProviderSeries\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.packetloss.v1.StatusR\x06status\x120\n" +
	"\x06series\x18\x05 \x03(\v2\x18.packetloss.v1.TimePointR\x06seriesBKZIgithub.com/exys/packetloss/builder/internal/pb/packetloss/v1;packetlossv1b\x06proto3"

var (
	file_packetloss_v1_artifacts_proto_rawDescOnce sync.Once
	file_packetloss_v1_artifacts_proto_rawDescData []byte
)

func file_packetloss_v1_artifacts_proto_rawDescGZIP() []byte {
	file_packetloss_v1_artifacts_proto_rawDescOnce.Do(func() {
		file_packetloss_v1_artifacts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packetloss_v1_artifacts_proto_rawDesc), len(file_packetloss_v1_artifacts_proto_rawDesc)))
	})
	return file_packetloss_v1_artifacts_proto_rawDescData
}

var file_packetloss_v1_artifacts_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_packetloss_v1_artifacts_proto_goTypes = []any{
	(*CountryList)(nil),      // 0: packetloss.v1.CountryList
	(*CountrySummary)(nil),   // 1: packetloss.v1.CountrySummary
	(*Overview)(nil),         // 2: packetloss.v1.Overview
	(*TargetRef)(nil),        // 3: packetloss.v1.TargetRef
	(*ProviderRow)(nil),      // 4: packetloss.v1.ProviderRow
	(*Cell)(nil),             // 5: packetloss.v1.Cell
	(*ProviderDetail)(nil),   // 6: packetloss.v1.ProviderDetail
	(*TargetSeries)(nil),     // 7: packetloss.v1.TargetSeries
	(*TargetComparison)(nil), // 8: packetloss.v1.TargetComparison
	(*ProviderSeries)(nil),   // 9: packetloss.v1.ProviderSeries
	(Status)(0),              // 10: packetloss.v1.Status
	(*TimePoint)(nil),        // 11: packetloss.v1.TimePoint
}
var file_packetloss_v1_artifacts_proto_depIdxs = []int32{
	1,  // 0: packetloss.v1.CountryList.countries:type_name -> packetloss.v1.CountrySummary
	3,  // 1: packetloss.v1.Overview.targets:type_name -> packetloss.v1.TargetRef
	4,  // 2: packetloss.v1.Overview.providers:type_name -> packetloss.v1.ProviderRow
	10, // 3: packetloss.v1.ProviderRow.status:type_name -> packetloss.v1.Status
	5,  // 4: packetloss.v1.ProviderRow.cells:type_name -> packetloss.v1.Cell
	10, // 5: packetloss.v1.Cell.status:type_name -> packetloss.v1.Status
	10, // 6: packetloss.v1.ProviderDetail.status:type_name -> packetloss.v1.Status
	7,  // 7: packetloss.v1.ProviderDetail.targets:type_name -> packetloss.v1.TargetSeries
	10, // 8: packetloss.v1.TargetSeries.status:type_name -> packetloss.v1.Status
	11, // 9: packetloss.v1.TargetSeries.series:type_name -> packetloss.v1.TimePoint
	9,  // 10: packetloss.v1.TargetComparison.providers:type_name -> packetloss.v1.ProviderSeries
	10, // 11: packetloss.v1.ProviderSeries.status:type_name -> packetloss.v1.Status
	11, // 12: packetloss.v1.ProviderSeries.series:type_name -> packetloss.v1.TimePoint
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_packetloss_v1_artifacts_proto_init() }
func file_packetloss_v1_artifacts_proto_init() {
	if File_packetloss_v1_artifacts_proto != nil {
		return
	}
	file_packetloss_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packetloss_v1_artifacts_proto_rawDesc), len(file_packetloss_v1_artifacts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packetloss_v1_artifacts_proto_goTypes,
		DependencyIndexes: file_packetloss_v1_artifacts_proto_depIdxs,
		MessageInfos:      file_packetloss_v1_artifacts_proto_msgTypes,
	}.Build()
	File_packetloss_v1_artifacts_proto = out.File
	file_packetloss_v1_artifacts_proto_goTypes = nil
	file_packetloss_v1_artifacts_proto_depIdxs = nil
}
