// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: packetloss/v1/common.proto

package packetlossv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health of a provider->target relationship, rendered as the grid cell colour.
// Derived from absolute thresholds (see config/thresholds.yaml), NOT the relative score.
type Status int32

const (
	Status_STATUS_UNSPECIFIED           Status = 0
	Status_STATUS_GREEN                 Status = 1 // within absolute RTT/loss thresholds
	Status_STATUS_AMBER                 Status = 2 // borderline
	Status_STATUS_RED                   Status = 3 // breaches thresholds
	Status_STATUS_INSUFFICIENT_COVERAGE Status = 4 // not enough probes to judge
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_GREEN",
		2: "STATUS_AMBER",
		3: "STATUS_RED",
		4: "STATUS_INSUFFICIENT_COVERAGE",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":           0,
		"STATUS_GREEN":                 1,
		"STATUS_AMBER":                 2,
		"STATUS_RED":                   3,
		"STATUS_INSUFFICIENT_COVERAGE": 4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_packetloss_v1_common_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_packetloss_v1_common_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_packetloss_v1_common_proto_rawDescGZIP(), []int{0}
}

// One point in a downsampled time series (one per measurement window).
type TimePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            string                 `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`                            // RFC3339
	RttMs         float64                `protobuf:"fixed64,2,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`       // window median RTT
	LossPct       float64                `protobuf:"fixed64,3,opt,name=loss_pct,json=lossPct,proto3" json:"loss_pct,omitempty"` // window mean loss
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimePoint) Reset() {
	*x = TimePoint{}
	mi := &file_packetloss_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimePoint) ProtoMessage() {}

func (x *TimePoint) ProtoReflect() protoreflect.Message {
	mi := &file_packetloss_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimePoint.ProtoReflect.Descriptor instead.
func (*TimePoint) Descriptor() ([]byte, []int) {
	return file_packetloss_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *TimePoint) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *TimePoint) GetRttMs() float64 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *TimePoint) GetLossPct() float64 {
	if x != nil {
		return x.LossPct
	}
	return 0
}

var File_packetloss_v1_common_proto protoreflect.FileDescriptor

const file_packetloss_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1apacketloss/v1/common.proto\x12\rpacketloss.v1\"M\n" +
	"\tTimePoint\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\tR\x02ts\x12\x15\n" +
	"\x06rtt_ms\x18\x02 \x01(\x01R\x05rttMs\x12\x19\n" +
	"\bloss_pct\x18\x03 \x01(\x01R\alossPct*v\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSTATUS_GREEN\x10\x01\x12\x10\n" +
	"\fSTATUS_AMBER\x10\x02\x12\x0e\n" +
	"\n" +
	"STATUS_RED\x10\x03\x12 \n" +
	"\x1cSTATUS_INSUFFICIENT_COVERAGE\x10\x04BKZIgithub.com/exys/packetloss/builder/internal/pb/packetloss/v1;packetlossv1b\x06proto3"

var (
	file_packetloss_v1_common_proto_rawDescOnce sync.Once
	file_packetloss_v1_common_proto_rawDescData []byte
)

func file_packetloss_v1_common_proto_rawDescGZIP() []byte {
	file_packetloss_v1_common_proto_rawDescOnce.Do(func() {
		file_packetloss_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packetloss_v1_common_proto_rawDesc), len(file_packetloss_v1_common_proto_rawDesc)))
	})
	return file_packetloss_v1_common_proto_rawDescData
}

var file_packetloss_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packetloss_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packetloss_v1_common_proto_goTypes = []any{
	(Status)(0),       // 0: packetloss.v1.Status
	(*TimePoint)(nil), // 1: packetloss.v1.TimePoint
}
var file_packetloss_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packetloss_v1_common_proto_init() }
func file_packetloss_v1_common_proto_init() {
	if File_packetloss_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packetloss_v1_common_proto_rawDesc), len(file_packetloss_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packetloss_v1_common_proto_goTypes,
		DependencyIndexes: file_packetloss_v1_common_proto_depIdxs,
		EnumInfos:         file_packetloss_v1_common_proto_enumTypes,
		MessageInfos:      file_packetloss_v1_common_proto_msgTypes,
	}.Build()
	File_packetloss_v1_common_proto = out.File
	file_packetloss_v1_common_proto_goTypes = nil
	file_packetloss_v1_common_proto_depIdxs = nil
}
